// File api.go is the gist of all network communication.
//
// It defines the interfaces and shared types for distributed Mandelbrot rendering.
// It is used by both server and client code to ensure consistent API contracts.
// Actual network code is in api_irpc.go and can be regenerated by calling 'go generate api.go'.
package api

import (
	"image"
	"time"
)

// Calling 'go generate api.go' will call 'irpc api.go', regenerating api_irpc.go code.
// ( $GOFILE represents current file )
//go:generate irpc $GOFILE

// ImgProvider is implemented by the server and is called by the CLI client to get the full image once rendering is complete.
type ImgProvider interface {
	// GetImage returns the fully rendered image.
	// Blocks until rendering is finished
	GetImage() (*image.RGBA, error)
}

// TileProvider is implemented by the server and used by the web client to show rendering progress tile by tile.
// Web clients use polling to check for updates (avoiding polling would complicate this demo too much).
type TileProvider interface {
	// FinishedTiles returns a map of rectangles of all finished tiles.
	FinishedTiles() (map[image.Rectangle]struct{}, error)
	// GetTileImg returns image of given rectangle.
	GetTileImg(rect image.Rectangle) (*image.RGBA, error)
	// FullImageDimensions returns the width and height of the full image.
	FullImageDimensions() (width, height int, err error)
	// TotalTilesCount returns the total count of tiles to be rendered.
	TotalTilesCount() (int, error)
	// WorkersCount returns the number of workers currently running.
	WorkersCount() (int, error)
}

// Renderer does the actual rendering work.
//
// It is implemented by all rendering clients (CLI and web) and called from the server.
type Renderer interface {
	// RenderTile renders a single tile of the Mandelbrot image.
	//   imgW, imgH: full image width and height
	RenderTile(reg MandelRegion, imgW, imgH int, tile image.Rectangle) (*image.RGBA, error)
}

// RenderTileSleepTime is used by all renderers (CLI and web) to slow down rendering, so the parallelization is more apparent.
var RenderTileSleepTime = 500 * time.Millisecond

// MandelRegion defines region within the Mandelbrot set.
type MandelRegion struct {
	Xmin, Xmax float64
	Ymin, Ymax float64
}
