// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc_dist_mandel/api.go
package mandel

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
	"image"
)

var _ImgProviderIrpcId = []byte{
	0xc6, 0x5f, 0xbc, 0x17, 0x2d, 0xed, 0xc9, 0x48,
	0xa0, 0x14, 0x59, 0x3e, 0x5b, 0x25, 0x5f, 0xb7,
	0x4e, 0x73, 0x4a, 0x05, 0x21, 0xc4, 0x5e, 0x7c,
	0x90, 0x13, 0x0c, 0xa0, 0xb8, 0x58, 0x89, 0xc1,
}

type ImgProviderIrpcService struct {
	impl ImgProvider
}

func NewImgProviderIrpcService(impl ImgProvider) *ImgProviderIrpcService {
	return &ImgProviderIrpcService{
		impl: impl,
	}
}
func (s *ImgProviderIrpcService) Id() []byte {
	return _ImgProviderIrpcId
}
func (s *ImgProviderIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // GetImage
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_ImgProvider_GetImageResp
				resp.p0, resp.p1 = s.impl.GetImage()
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// ImgProviderIrpcClient implements ImgProvider
//
// ImgProvider is implemented by the server and called by the CLI client to get the full image once rendering is complete.
type ImgProviderIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func NewImgProviderIrpcClient(endpoint irpcgen.Endpoint) (*ImgProviderIrpcClient, error) {
	if err := endpoint.RegisterClient(_ImgProviderIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &ImgProviderIrpcClient{endpoint: endpoint}, nil
}

// GetImage returns the fully rendered image.
// Returns: image.RGBA pointer and error if retrieval fails.
func (_c *ImgProviderIrpcClient) GetImage() (*image.RGBA, error) {
	var resp _irpc_ImgProvider_GetImageResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _ImgProviderIrpcId, 0, irpcgen.EmptySerializable{}, &resp); err != nil {
		var zero _irpc_ImgProvider_GetImageResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

type _irpc_ImgProvider_GetImageResp struct {
	p0 *image.RGBA
	p1 error
}

func (s _irpc_ImgProvider_GetImageResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, pt *image.RGBA) error {
		return irpcgen.EncPointer(enc, pt, "image.RGBA", func(enc *irpcgen.Encoder, s image.RGBA) error {
			if err := irpcgen.EncByteSlice(enc, s.Pix); err != nil {
				return fmt.Errorf("serialize s.Pix of type []uint8: %w", err)
			}
			if err := irpcgen.EncInt(enc, s.Stride); err != nil {
				return fmt.Errorf("serialize s.Stride of type int: %w", err)
			}
			if err := func(enc *irpcgen.Encoder, s image.Rectangle) error {
				if err := func(enc *irpcgen.Encoder, s image.Point) error {
					if err := irpcgen.EncInt(enc, s.X); err != nil {
						return fmt.Errorf("serialize s.X of type int: %w", err)
					}
					if err := irpcgen.EncInt(enc, s.Y); err != nil {
						return fmt.Errorf("serialize s.Y of type int: %w", err)
					}
					return nil
				}(enc, s.Min); err != nil {
					return fmt.Errorf("serialize s.Min of type image.Point: %w", err)
				}
				if err := func(enc *irpcgen.Encoder, s image.Point) error {
					if err := irpcgen.EncInt(enc, s.X); err != nil {
						return fmt.Errorf("serialize s.X of type int: %w", err)
					}
					if err := irpcgen.EncInt(enc, s.Y); err != nil {
						return fmt.Errorf("serialize s.Y of type int: %w", err)
					}
					return nil
				}(enc, s.Max); err != nil {
					return fmt.Errorf("serialize s.Max of type image.Point: %w", err)
				}
				return nil
			}(enc, s.Rect); err != nil {
				return fmt.Errorf("serialize s.Rect of type image.Rectangle: %w", err)
			}
			return nil
		})
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type *image.RGBA: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_ImgProvider_GetImageResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, pt **image.RGBA) error {
		return irpcgen.DecPointer(dec, pt, "image.RGBA", func(dec *irpcgen.Decoder, s *image.RGBA) error {
			if err := irpcgen.DecByteSlice(dec, &s.Pix); err != nil {
				return fmt.Errorf("deserialize s.Pix of type []uint8: %w", err)
			}
			if err := irpcgen.DecInt(dec, &s.Stride); err != nil {
				return fmt.Errorf("deserialize s.Stride of type int: %w", err)
			}
			if err := func(dec *irpcgen.Decoder, s *image.Rectangle) error {
				if err := func(dec *irpcgen.Decoder, s *image.Point) error {
					if err := irpcgen.DecInt(dec, &s.X); err != nil {
						return fmt.Errorf("deserialize s.X of type int: %w", err)
					}
					if err := irpcgen.DecInt(dec, &s.Y); err != nil {
						return fmt.Errorf("deserialize s.Y of type int: %w", err)
					}
					return nil
				}(dec, &s.Min); err != nil {
					return fmt.Errorf("deserialize s.Min of type image.Point: %w", err)
				}
				if err := func(dec *irpcgen.Decoder, s *image.Point) error {
					if err := irpcgen.DecInt(dec, &s.X); err != nil {
						return fmt.Errorf("deserialize s.X of type int: %w", err)
					}
					if err := irpcgen.DecInt(dec, &s.Y); err != nil {
						return fmt.Errorf("deserialize s.Y of type int: %w", err)
					}
					return nil
				}(dec, &s.Max); err != nil {
					return fmt.Errorf("deserialize s.Max of type image.Point: %w", err)
				}
				return nil
			}(dec, &s.Rect); err != nil {
				return fmt.Errorf("deserialize s.Rect of type image.Rectangle: %w", err)
			}
			return nil
		})
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type *image.RGBA: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_ImgProvider_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _error_ImgProvider_impl struct {
	_Error_0_ string
}

func (i _error_ImgProvider_impl) Error() string {
	return i._Error_0_
}

var _TileProviderIrpcId = []byte{
	0x5d, 0xec, 0xc4, 0x4a, 0xd5, 0x47, 0x4d, 0x4d,
	0x68, 0xc7, 0x30, 0x08, 0x5c, 0xf4, 0xe5, 0xdd,
	0x37, 0x26, 0xcf, 0x0b, 0xa6, 0xff, 0x20, 0x70,
	0xdc, 0x26, 0xac, 0x4c, 0x72, 0xb6, 0x40, 0xa7,
}

type TileProviderIrpcService struct {
	impl TileProvider
}

func NewTileProviderIrpcService(impl TileProvider) *TileProviderIrpcService {
	return &TileProviderIrpcService{
		impl: impl,
	}
}
func (s *TileProviderIrpcService) Id() []byte {
	return _TileProviderIrpcId
}
func (s *TileProviderIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // FinishedTiles
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TileProvider_FinishedTilesResp
				resp.p0, resp.p1 = s.impl.FinishedTiles()
				return resp
			}, nil
		}, nil
	case 1: // GetTileImg
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_TileProvider_GetTileImgReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TileProvider_GetTileImgResp
				resp.p0, resp.p1 = s.impl.GetTileImg(args.rect)
				return resp
			}, nil
		}, nil
	case 2: // FullImageDimensions
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TileProvider_FullImageDimensionsResp
				resp.width, resp.height, resp.err = s.impl.FullImageDimensions()
				return resp
			}, nil
		}, nil
	case 3: // TotalTilesNumber
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TileProvider_TotalTilesNumberResp
				resp.p0, resp.p1 = s.impl.TotalTilesNumber()
				return resp
			}, nil
		}, nil
	case 4: // Workers
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TileProvider_WorkersResp
				resp.p0, resp.p1 = s.impl.Workers()
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// TileProviderIrpcClient implements TileProvider
//
// TileProvider is implemented by the server and used by the web client to show rendering progress tile by tile.
// Web clients use polling to check for updates.
type TileProviderIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func NewTileProviderIrpcClient(endpoint irpcgen.Endpoint) (*TileProviderIrpcClient, error) {
	if err := endpoint.RegisterClient(_TileProviderIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &TileProviderIrpcClient{endpoint: endpoint}, nil
}

// FinishedTiles returns a map of finished tile rectangles.
func (_c *TileProviderIrpcClient) FinishedTiles() (map[image.Rectangle]struct{}, error) {
	var resp _irpc_TileProvider_FinishedTilesResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _TileProviderIrpcId, 0, irpcgen.EmptySerializable{}, &resp); err != nil {
		var zero _irpc_TileProvider_FinishedTilesResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

// GetTileImg returns the image for a specific tile rectangle.
func (_c *TileProviderIrpcClient) GetTileImg(rect image.Rectangle) (*image.RGBA, error) {
	var req = _irpc_TileProvider_GetTileImgReq{
		rect: rect,
	}
	var resp _irpc_TileProvider_GetTileImgResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _TileProviderIrpcId, 1, req, &resp); err != nil {
		var zero _irpc_TileProvider_GetTileImgResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

// FullImageDimensions returns the width and height of the full image.
func (_c *TileProviderIrpcClient) FullImageDimensions() (width int, height int, err error) {
	var resp _irpc_TileProvider_FullImageDimensionsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _TileProviderIrpcId, 2, irpcgen.EmptySerializable{}, &resp); err != nil {
		var zero _irpc_TileProvider_FullImageDimensionsResp
		return zero.width, zero.height, err
	}
	return resp.width, resp.height, resp.err
}

// TotalTilesNumber returns the total number of tiles to be rendered.
func (_c *TileProviderIrpcClient) TotalTilesNumber() (int, error) {
	var resp _irpc_TileProvider_TotalTilesNumberResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _TileProviderIrpcId, 3, irpcgen.EmptySerializable{}, &resp); err != nil {
		var zero _irpc_TileProvider_TotalTilesNumberResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

// Workers returns the number of workers currently running.
func (_c *TileProviderIrpcClient) Workers() (int, error) {
	var resp _irpc_TileProvider_WorkersResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _TileProviderIrpcId, 4, irpcgen.EmptySerializable{}, &resp); err != nil {
		var zero _irpc_TileProvider_WorkersResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

type _irpc_TileProvider_FinishedTilesResp struct {
	p0 map[image.Rectangle]struct{}
	p1 error
}

func (s _irpc_TileProvider_FinishedTilesResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, m map[image.Rectangle]struct{}) error {
		return irpcgen.EncMap(enc, m, "image.Rectangle", func(enc *irpcgen.Encoder, s image.Rectangle) error {
			if err := func(enc *irpcgen.Encoder, s image.Point) error {
				if err := irpcgen.EncInt(enc, s.X); err != nil {
					return fmt.Errorf("serialize s.X of type int: %w", err)
				}
				if err := irpcgen.EncInt(enc, s.Y); err != nil {
					return fmt.Errorf("serialize s.Y of type int: %w", err)
				}
				return nil
			}(enc, s.Min); err != nil {
				return fmt.Errorf("serialize s.Min of type image.Point: %w", err)
			}
			if err := func(enc *irpcgen.Encoder, s image.Point) error {
				if err := irpcgen.EncInt(enc, s.X); err != nil {
					return fmt.Errorf("serialize s.X of type int: %w", err)
				}
				if err := irpcgen.EncInt(enc, s.Y); err != nil {
					return fmt.Errorf("serialize s.Y of type int: %w", err)
				}
				return nil
			}(enc, s.Max); err != nil {
				return fmt.Errorf("serialize s.Max of type image.Point: %w", err)
			}
			return nil
		}, "struct{}", func(enc *irpcgen.Encoder, s struct{}) error {
			return nil
		})
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type map[image.Rectangle]struct{}: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_TileProvider_FinishedTilesResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, m *map[image.Rectangle]struct{}) error {
		return irpcgen.DecMap(dec, m, "image.Rectangle", func(dec *irpcgen.Decoder, s *image.Rectangle) error {
			if err := func(dec *irpcgen.Decoder, s *image.Point) error {
				if err := irpcgen.DecInt(dec, &s.X); err != nil {
					return fmt.Errorf("deserialize s.X of type int: %w", err)
				}
				if err := irpcgen.DecInt(dec, &s.Y); err != nil {
					return fmt.Errorf("deserialize s.Y of type int: %w", err)
				}
				return nil
			}(dec, &s.Min); err != nil {
				return fmt.Errorf("deserialize s.Min of type image.Point: %w", err)
			}
			if err := func(dec *irpcgen.Decoder, s *image.Point) error {
				if err := irpcgen.DecInt(dec, &s.X); err != nil {
					return fmt.Errorf("deserialize s.X of type int: %w", err)
				}
				if err := irpcgen.DecInt(dec, &s.Y); err != nil {
					return fmt.Errorf("deserialize s.Y of type int: %w", err)
				}
				return nil
			}(dec, &s.Max); err != nil {
				return fmt.Errorf("deserialize s.Max of type image.Point: %w", err)
			}
			return nil
		}, "struct{}", func(dec *irpcgen.Decoder, s *struct{}) error {
			return nil
		})
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type map[image.Rectangle]struct{}: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_TileProvider_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _error_TileProvider_impl struct {
	_Error_0_ string
}

func (i _error_TileProvider_impl) Error() string {
	return i._Error_0_
}

type _irpc_TileProvider_GetTileImgReq struct {
	rect image.Rectangle
}

func (s _irpc_TileProvider_GetTileImgReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, s image.Rectangle) error {
		if err := func(enc *irpcgen.Encoder, s image.Point) error {
			if err := irpcgen.EncInt(enc, s.X); err != nil {
				return fmt.Errorf("serialize s.X of type int: %w", err)
			}
			if err := irpcgen.EncInt(enc, s.Y); err != nil {
				return fmt.Errorf("serialize s.Y of type int: %w", err)
			}
			return nil
		}(enc, s.Min); err != nil {
			return fmt.Errorf("serialize s.Min of type image.Point: %w", err)
		}
		if err := func(enc *irpcgen.Encoder, s image.Point) error {
			if err := irpcgen.EncInt(enc, s.X); err != nil {
				return fmt.Errorf("serialize s.X of type int: %w", err)
			}
			if err := irpcgen.EncInt(enc, s.Y); err != nil {
				return fmt.Errorf("serialize s.Y of type int: %w", err)
			}
			return nil
		}(enc, s.Max); err != nil {
			return fmt.Errorf("serialize s.Max of type image.Point: %w", err)
		}
		return nil
	}(e, s.rect); err != nil {
		return fmt.Errorf("serialize \"rect\" of type image.Rectangle: %w", err)
	}
	return nil
}
func (s *_irpc_TileProvider_GetTileImgReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *image.Rectangle) error {
		if err := func(dec *irpcgen.Decoder, s *image.Point) error {
			if err := irpcgen.DecInt(dec, &s.X); err != nil {
				return fmt.Errorf("deserialize s.X of type int: %w", err)
			}
			if err := irpcgen.DecInt(dec, &s.Y); err != nil {
				return fmt.Errorf("deserialize s.Y of type int: %w", err)
			}
			return nil
		}(dec, &s.Min); err != nil {
			return fmt.Errorf("deserialize s.Min of type image.Point: %w", err)
		}
		if err := func(dec *irpcgen.Decoder, s *image.Point) error {
			if err := irpcgen.DecInt(dec, &s.X); err != nil {
				return fmt.Errorf("deserialize s.X of type int: %w", err)
			}
			if err := irpcgen.DecInt(dec, &s.Y); err != nil {
				return fmt.Errorf("deserialize s.Y of type int: %w", err)
			}
			return nil
		}(dec, &s.Max); err != nil {
			return fmt.Errorf("deserialize s.Max of type image.Point: %w", err)
		}
		return nil
	}(d, &s.rect); err != nil {
		return fmt.Errorf("deserialize rect of type image.Rectangle: %w", err)
	}
	return nil
}

type _irpc_TileProvider_GetTileImgResp struct {
	p0 *image.RGBA
	p1 error
}

func (s _irpc_TileProvider_GetTileImgResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, pt *image.RGBA) error {
		return irpcgen.EncPointer(enc, pt, "image.RGBA", func(enc *irpcgen.Encoder, s image.RGBA) error {
			if err := irpcgen.EncByteSlice(enc, s.Pix); err != nil {
				return fmt.Errorf("serialize s.Pix of type []uint8: %w", err)
			}
			if err := irpcgen.EncInt(enc, s.Stride); err != nil {
				return fmt.Errorf("serialize s.Stride of type int: %w", err)
			}
			if err := func(enc *irpcgen.Encoder, s image.Rectangle) error {
				if err := func(enc *irpcgen.Encoder, s image.Point) error {
					if err := irpcgen.EncInt(enc, s.X); err != nil {
						return fmt.Errorf("serialize s.X of type int: %w", err)
					}
					if err := irpcgen.EncInt(enc, s.Y); err != nil {
						return fmt.Errorf("serialize s.Y of type int: %w", err)
					}
					return nil
				}(enc, s.Min); err != nil {
					return fmt.Errorf("serialize s.Min of type image.Point: %w", err)
				}
				if err := func(enc *irpcgen.Encoder, s image.Point) error {
					if err := irpcgen.EncInt(enc, s.X); err != nil {
						return fmt.Errorf("serialize s.X of type int: %w", err)
					}
					if err := irpcgen.EncInt(enc, s.Y); err != nil {
						return fmt.Errorf("serialize s.Y of type int: %w", err)
					}
					return nil
				}(enc, s.Max); err != nil {
					return fmt.Errorf("serialize s.Max of type image.Point: %w", err)
				}
				return nil
			}(enc, s.Rect); err != nil {
				return fmt.Errorf("serialize s.Rect of type image.Rectangle: %w", err)
			}
			return nil
		})
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type *image.RGBA: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_TileProvider_GetTileImgResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, pt **image.RGBA) error {
		return irpcgen.DecPointer(dec, pt, "image.RGBA", func(dec *irpcgen.Decoder, s *image.RGBA) error {
			if err := irpcgen.DecByteSlice(dec, &s.Pix); err != nil {
				return fmt.Errorf("deserialize s.Pix of type []uint8: %w", err)
			}
			if err := irpcgen.DecInt(dec, &s.Stride); err != nil {
				return fmt.Errorf("deserialize s.Stride of type int: %w", err)
			}
			if err := func(dec *irpcgen.Decoder, s *image.Rectangle) error {
				if err := func(dec *irpcgen.Decoder, s *image.Point) error {
					if err := irpcgen.DecInt(dec, &s.X); err != nil {
						return fmt.Errorf("deserialize s.X of type int: %w", err)
					}
					if err := irpcgen.DecInt(dec, &s.Y); err != nil {
						return fmt.Errorf("deserialize s.Y of type int: %w", err)
					}
					return nil
				}(dec, &s.Min); err != nil {
					return fmt.Errorf("deserialize s.Min of type image.Point: %w", err)
				}
				if err := func(dec *irpcgen.Decoder, s *image.Point) error {
					if err := irpcgen.DecInt(dec, &s.X); err != nil {
						return fmt.Errorf("deserialize s.X of type int: %w", err)
					}
					if err := irpcgen.DecInt(dec, &s.Y); err != nil {
						return fmt.Errorf("deserialize s.Y of type int: %w", err)
					}
					return nil
				}(dec, &s.Max); err != nil {
					return fmt.Errorf("deserialize s.Max of type image.Point: %w", err)
				}
				return nil
			}(dec, &s.Rect); err != nil {
				return fmt.Errorf("deserialize s.Rect of type image.Rectangle: %w", err)
			}
			return nil
		})
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type *image.RGBA: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_TileProvider_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _irpc_TileProvider_FullImageDimensionsResp struct {
	width  int
	height int
	err    error
}

func (s _irpc_TileProvider_FullImageDimensionsResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.width); err != nil {
		return fmt.Errorf("serialize \"width\" of type int: %w", err)
	}
	if err := irpcgen.EncInt(e, s.height); err != nil {
		return fmt.Errorf("serialize \"height\" of type int: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.err); err != nil {
		return fmt.Errorf("serialize \"err\" of type error: %w", err)
	}
	return nil
}
func (s *_irpc_TileProvider_FullImageDimensionsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.width); err != nil {
		return fmt.Errorf("deserialize width of type int: %w", err)
	}
	if err := irpcgen.DecInt(d, &s.height); err != nil {
		return fmt.Errorf("deserialize height of type int: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_TileProvider_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.err); err != nil {
		return fmt.Errorf("deserialize err of type error: %w", err)
	}
	return nil
}

type _irpc_TileProvider_TotalTilesNumberResp struct {
	p0 int
	p1 error
}

func (s _irpc_TileProvider_TotalTilesNumberResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_TileProvider_TotalTilesNumberResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_TileProvider_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _irpc_TileProvider_WorkersResp struct {
	p0 int
	p1 error
}

func (s _irpc_TileProvider_WorkersResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_TileProvider_WorkersResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_TileProvider_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

var _RendererIrpcId = []byte{
	0x40, 0xdb, 0x9d, 0x9f, 0xf1, 0x00, 0xb0, 0xe1,
	0xfc, 0x10, 0x54, 0x7f, 0xa9, 0x28, 0xf7, 0xd3,
	0x80, 0xb0, 0xce, 0x58, 0x71, 0xb0, 0xab, 0x61,
	0xab, 0x13, 0xe2, 0xe5, 0x43, 0x03, 0xed, 0xe1,
}

type RendererIrpcService struct {
	impl Renderer
}

func NewRendererIrpcService(impl Renderer) *RendererIrpcService {
	return &RendererIrpcService{
		impl: impl,
	}
}
func (s *RendererIrpcService) Id() []byte {
	return _RendererIrpcId
}
func (s *RendererIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // RenderTile
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_Renderer_RenderTileReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_Renderer_RenderTileResp
				resp.p0, resp.p1 = s.impl.RenderTile(args.r, args.tile, args.imgW, args.imgH)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// RendererIrpcClient implements Renderer
//
// Renderer is implemented by all rendering clients (CLI and web) and called from the server.
type RendererIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func NewRendererIrpcClient(endpoint irpcgen.Endpoint) (*RendererIrpcClient, error) {
	if err := endpoint.RegisterClient(_RendererIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &RendererIrpcClient{endpoint: endpoint}, nil
}

// RenderTile renders a single tile of the Mandelbrot image.
//   r: region of the Mandelbrot set to render
//   tile: rectangle specifying the tile area
//   imgW, imgH: full image width and height
// Returns: image.RGBA pointer for the tile, and error if rendering fails.
func (_c *RendererIrpcClient) RenderTile(r Region, tile image.Rectangle, imgW int, imgH int) (*image.RGBA, error) {
	var req = _irpc_Renderer_RenderTileReq{
		r:    r,
		tile: tile,
		imgW: imgW,
		imgH: imgH,
	}
	var resp _irpc_Renderer_RenderTileResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _RendererIrpcId, 0, req, &resp); err != nil {
		var zero _irpc_Renderer_RenderTileResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

type _irpc_Renderer_RenderTileReq struct {
	r    Region
	tile image.Rectangle
	imgW int
	imgH int
}

func (s _irpc_Renderer_RenderTileReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, s Region) error {
		if err := irpcgen.EncFloat64(enc, s.Xmin); err != nil {
			return fmt.Errorf("serialize s.Xmin of type float64: %w", err)
		}
		if err := irpcgen.EncFloat64(enc, s.Xmax); err != nil {
			return fmt.Errorf("serialize s.Xmax of type float64: %w", err)
		}
		if err := irpcgen.EncFloat64(enc, s.Ymin); err != nil {
			return fmt.Errorf("serialize s.Ymin of type float64: %w", err)
		}
		if err := irpcgen.EncFloat64(enc, s.Ymax); err != nil {
			return fmt.Errorf("serialize s.Ymax of type float64: %w", err)
		}
		return nil
	}(e, s.r); err != nil {
		return fmt.Errorf("serialize \"r\" of type Region: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, s image.Rectangle) error {
		if err := func(enc *irpcgen.Encoder, s image.Point) error {
			if err := irpcgen.EncInt(enc, s.X); err != nil {
				return fmt.Errorf("serialize s.X of type int: %w", err)
			}
			if err := irpcgen.EncInt(enc, s.Y); err != nil {
				return fmt.Errorf("serialize s.Y of type int: %w", err)
			}
			return nil
		}(enc, s.Min); err != nil {
			return fmt.Errorf("serialize s.Min of type image.Point: %w", err)
		}
		if err := func(enc *irpcgen.Encoder, s image.Point) error {
			if err := irpcgen.EncInt(enc, s.X); err != nil {
				return fmt.Errorf("serialize s.X of type int: %w", err)
			}
			if err := irpcgen.EncInt(enc, s.Y); err != nil {
				return fmt.Errorf("serialize s.Y of type int: %w", err)
			}
			return nil
		}(enc, s.Max); err != nil {
			return fmt.Errorf("serialize s.Max of type image.Point: %w", err)
		}
		return nil
	}(e, s.tile); err != nil {
		return fmt.Errorf("serialize \"tile\" of type image.Rectangle: %w", err)
	}
	if err := irpcgen.EncInt(e, s.imgW); err != nil {
		return fmt.Errorf("serialize \"imgW\" of type int: %w", err)
	}
	if err := irpcgen.EncInt(e, s.imgH); err != nil {
		return fmt.Errorf("serialize \"imgH\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_Renderer_RenderTileReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *Region) error {
		if err := irpcgen.DecFloat64(dec, &s.Xmin); err != nil {
			return fmt.Errorf("deserialize s.Xmin of type float64: %w", err)
		}
		if err := irpcgen.DecFloat64(dec, &s.Xmax); err != nil {
			return fmt.Errorf("deserialize s.Xmax of type float64: %w", err)
		}
		if err := irpcgen.DecFloat64(dec, &s.Ymin); err != nil {
			return fmt.Errorf("deserialize s.Ymin of type float64: %w", err)
		}
		if err := irpcgen.DecFloat64(dec, &s.Ymax); err != nil {
			return fmt.Errorf("deserialize s.Ymax of type float64: %w", err)
		}
		return nil
	}(d, &s.r); err != nil {
		return fmt.Errorf("deserialize r of type Region: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *image.Rectangle) error {
		if err := func(dec *irpcgen.Decoder, s *image.Point) error {
			if err := irpcgen.DecInt(dec, &s.X); err != nil {
				return fmt.Errorf("deserialize s.X of type int: %w", err)
			}
			if err := irpcgen.DecInt(dec, &s.Y); err != nil {
				return fmt.Errorf("deserialize s.Y of type int: %w", err)
			}
			return nil
		}(dec, &s.Min); err != nil {
			return fmt.Errorf("deserialize s.Min of type image.Point: %w", err)
		}
		if err := func(dec *irpcgen.Decoder, s *image.Point) error {
			if err := irpcgen.DecInt(dec, &s.X); err != nil {
				return fmt.Errorf("deserialize s.X of type int: %w", err)
			}
			if err := irpcgen.DecInt(dec, &s.Y); err != nil {
				return fmt.Errorf("deserialize s.Y of type int: %w", err)
			}
			return nil
		}(dec, &s.Max); err != nil {
			return fmt.Errorf("deserialize s.Max of type image.Point: %w", err)
		}
		return nil
	}(d, &s.tile); err != nil {
		return fmt.Errorf("deserialize tile of type image.Rectangle: %w", err)
	}
	if err := irpcgen.DecInt(d, &s.imgW); err != nil {
		return fmt.Errorf("deserialize imgW of type int: %w", err)
	}
	if err := irpcgen.DecInt(d, &s.imgH); err != nil {
		return fmt.Errorf("deserialize imgH of type int: %w", err)
	}
	return nil
}

type _irpc_Renderer_RenderTileResp struct {
	p0 *image.RGBA
	p1 error
}

func (s _irpc_Renderer_RenderTileResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, pt *image.RGBA) error {
		return irpcgen.EncPointer(enc, pt, "image.RGBA", func(enc *irpcgen.Encoder, s image.RGBA) error {
			if err := irpcgen.EncByteSlice(enc, s.Pix); err != nil {
				return fmt.Errorf("serialize s.Pix of type []uint8: %w", err)
			}
			if err := irpcgen.EncInt(enc, s.Stride); err != nil {
				return fmt.Errorf("serialize s.Stride of type int: %w", err)
			}
			if err := func(enc *irpcgen.Encoder, s image.Rectangle) error {
				if err := func(enc *irpcgen.Encoder, s image.Point) error {
					if err := irpcgen.EncInt(enc, s.X); err != nil {
						return fmt.Errorf("serialize s.X of type int: %w", err)
					}
					if err := irpcgen.EncInt(enc, s.Y); err != nil {
						return fmt.Errorf("serialize s.Y of type int: %w", err)
					}
					return nil
				}(enc, s.Min); err != nil {
					return fmt.Errorf("serialize s.Min of type image.Point: %w", err)
				}
				if err := func(enc *irpcgen.Encoder, s image.Point) error {
					if err := irpcgen.EncInt(enc, s.X); err != nil {
						return fmt.Errorf("serialize s.X of type int: %w", err)
					}
					if err := irpcgen.EncInt(enc, s.Y); err != nil {
						return fmt.Errorf("serialize s.Y of type int: %w", err)
					}
					return nil
				}(enc, s.Max); err != nil {
					return fmt.Errorf("serialize s.Max of type image.Point: %w", err)
				}
				return nil
			}(enc, s.Rect); err != nil {
				return fmt.Errorf("serialize s.Rect of type image.Rectangle: %w", err)
			}
			return nil
		})
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type *image.RGBA: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_Renderer_RenderTileResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, pt **image.RGBA) error {
		return irpcgen.DecPointer(dec, pt, "image.RGBA", func(dec *irpcgen.Decoder, s *image.RGBA) error {
			if err := irpcgen.DecByteSlice(dec, &s.Pix); err != nil {
				return fmt.Errorf("deserialize s.Pix of type []uint8: %w", err)
			}
			if err := irpcgen.DecInt(dec, &s.Stride); err != nil {
				return fmt.Errorf("deserialize s.Stride of type int: %w", err)
			}
			if err := func(dec *irpcgen.Decoder, s *image.Rectangle) error {
				if err := func(dec *irpcgen.Decoder, s *image.Point) error {
					if err := irpcgen.DecInt(dec, &s.X); err != nil {
						return fmt.Errorf("deserialize s.X of type int: %w", err)
					}
					if err := irpcgen.DecInt(dec, &s.Y); err != nil {
						return fmt.Errorf("deserialize s.Y of type int: %w", err)
					}
					return nil
				}(dec, &s.Min); err != nil {
					return fmt.Errorf("deserialize s.Min of type image.Point: %w", err)
				}
				if err := func(dec *irpcgen.Decoder, s *image.Point) error {
					if err := irpcgen.DecInt(dec, &s.X); err != nil {
						return fmt.Errorf("deserialize s.X of type int: %w", err)
					}
					if err := irpcgen.DecInt(dec, &s.Y); err != nil {
						return fmt.Errorf("deserialize s.Y of type int: %w", err)
					}
					return nil
				}(dec, &s.Max); err != nil {
					return fmt.Errorf("deserialize s.Max of type image.Point: %w", err)
				}
				return nil
			}(dec, &s.Rect); err != nil {
				return fmt.Errorf("deserialize s.Rect of type image.Rectangle: %w", err)
			}
			return nil
		})
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type *image.RGBA: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_Renderer_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _error_Renderer_impl struct {
	_Error_0_ string
}

func (i _error_Renderer_impl) Error() string {
	return i._Error_0_
}
